// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu1OjDBHI3hTx3MmkHGIp7N-pukkonvx0',
    appId: '1:506040630131:android:68292ffa4d3fb09fcaa306',
    messagingSenderId: '506040630131',
    projectId: 'docu-328ff',
    storageBucket: 'docu-328ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHFaKujFw7eqnUrQirvG487SHOzocS9jM',
    appId: '1:506040630131:ios:3f9f9074c880fd26caa306',
    messagingSenderId: '506040630131',
    projectId: 'docu-328ff',
    storageBucket: 'docu-328ff.appspot.com',
    androidClientId: '506040630131-hmpbs7e6veli15at09et8pe0ickhrmvd.apps.googleusercontent.com',
    iosClientId: '506040630131-31dc9ivdjrgiotg50sriki20m7r01phj.apps.googleusercontent.com',
    iosBundleId: 'com.example.docu',
  );
}
